# Generated by Django 4.0.6 on 2022-08-09 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=128)),
                ('content', models.CharField(max_length=256)),
            ],
            options={
                'db_table': 'comments',
            },
        ),
    ]
